apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPComputeServiceAccountConstraintV1
metadata:
  name: no_default_service_account
  annotations:
    description: GCE VMs cannot use default service account.
    category: Identity and Access Management
    documentation: https://github.com/adeo/DataFactoryArchitecture/blob/master/Heimdall-Manual/components/gce_instance_service_account.md
spec:
  severity: major
  match:
    target: [organization/] # to_be_adapted
    exclude:
  parameters:
    mode: "blacklist"
    match_mode: "regex"
    service_accounts: 
      - "[0-9]*-compute@developer.gserviceaccount.com"
