# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: CIGroupSettingsConstraintV1
metadata:
  name: external_members_denied_on_secgroups
  annotations:
    description: allowExternalMembers must be false for all groups.
    category: Identity and Access Management
spec:
  severity: major
  match:
    target: [directories/] # to_be_adapted
    exclude:
  parameters:
    group_selector:
      email:  # GLOB, with . and @ as separators !!!! ALL LOWERCASE
        - '**' # to_be_adapted
      email_mode: "whitelist"
      description: # Regexp
        - '^Mailing List.*' # to_be_adapted
        - '^Collaborative mailbox.*' # to_be_adapted
      description_mode: "blacklist"
    settings: # to_be_adapted
      allowExternalMembers: "true"
    settings_mode: "blacklist"
    exemptions: [] # array of group email to ignore
    
    
